### ISSUE TITLE
Code completion does not work.

### ISSUE THREAD

**Issue by misaz** [cypresssemiconductorco/mtb-example-psoc6-empty-app#1]
When I create project using this template in ModusToolbox Code completion in eclipse environment of ModusToolbox does not works. It is beacause include locations are not confiogured properly. In some other templates (like Wi-Fi project example) it works correctly. I "patched" it using manually defining include following folders (determined from compilation output) but I like to see working it out of box.

```
../mtb_shared/TARGET_CY8CKIT-062S2-43012/latest-v2.X
../mtb_shared/TARGET_CY8CKIT-062S2-43012/latest-v2.X/COMPONENT_BSP_DESIGN_MODUS
../mtb_shared/TARGET_CY8CKIT-062S2-43012/latest-v2.X/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource
../mtb_shared/capsense/latest-v2.X
../mtb_shared/core-lib/latest-v1.X
../mtb_shared/core-lib/latest-v1.X/include
../mtb_shared/mtb-hal-cat1/latest-v1.X
../mtb_shared/mtb-hal-cat1/latest-v1.X/COMPONENT_PSOC6HAL
../mtb_shared/mtb-hal-cat1/latest-v1.X/COMPONENT_PSOC6HAL/include
../mtb_shared/mtb-hal-cat1/latest-v1.X/COMPONENT_PSOC6HAL/include/pin_packages
../mtb_shared/mtb-hal-cat1/latest-v1.X/COMPONENT_PSOC6HAL/include/triggers
../mtb_shared/mtb-hal-cat1/latest-v1.X/include
../mtb_shared/mtb-pdl-cat1/latest-v2.X
../mtb_shared/mtb-pdl-cat1/latest-v2.X/cmsis
../mtb_shared/mtb-pdl-cat1/latest-v2.X/cmsis/include
../mtb_shared/mtb-pdl-cat1/latest-v2.X/devices
../mtb_shared/mtb-pdl-cat1/latest-v2.X/devices/COMPONENT_CAT1A
../mtb_shared/mtb-pdl-cat1/latest-v2.X/devices/COMPONENT_CAT1A/include
../mtb_shared/mtb-pdl-cat1/latest-v2.X/devices/COMPONENT_CAT1A/include/ip
../mtb_shared/mtb-pdl-cat1/latest-v2.X/drivers
../mtb_shared/mtb-pdl-cat1/latest-v2.X/drivers/include
../mtb_shared/retarget-io/latest-v1.X
```

**Comment by ddka22** [comment]
Hello @misaz , 

I created a project with this project template and was able to build successfully. Code completion options are being shown correctly. One of the things you could check is if your Content Assist eclipse option is disabled.

Under **Windows > Preferences > C/C++ >  Editor > Content Assist**, make sure all the options are checked. 

Hope this helps! :)

**Comment by vmedcy** [comment]
Hello, have you tried to build the project before using the code completion feature? The Eclipse C/C++ plugin parses the GCC build output log to automatically determine the project settings like include paths, macros etc - as configured in the project "Properties -> C/C++ General -> Preprocessor Include Paths, Macros etc -> Providers". Sometimes it is necessary to additionally execute "Clean" before "Build".

**Comment by misaz** [comment]
@ddka22 and @vmedcy Thank you for informations. I found an issue. It was because I have installed ModusToolbox to another drive different from default offered by installer. Now I have reinstalled ModusToolbox to user directory at main drive and everything works as expected with all templates including this one.
